# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [52]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [53]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [7]:
a30, b30 = np.random.random(10), np.random.random(10)
print(a30, b30)
print(np.intersect1d(a30, b30))

[0.09828761 0.39757962 0.11229596 0.53235976 0.54882815 0.42669246
 0.80907996 0.0748173  0.52701744 0.08048706] [8.91088272e-01 1.24380916e-02 9.85418231e-01 9.85280365e-01
 8.31930141e-05 8.01921527e-01 3.72766488e-01 7.16709650e-01
 7.53677215e-01 2.13275788e-01]
[]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [8]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2021-02-02 2021-02-09 2021-02-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [15]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [16]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [18]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[6.0734212  8.42868379 0.98570001 8.77494954 8.7469607  1.8303016
 3.90594981 3.01033581 5.44821013 4.03837716]
[6. 8. 0. 8. 8. 1. 3. 3. 5. 4.]
[6. 8. 0. 8. 8. 1. 3. 3. 5. 4.]
[6. 8. 0. 8. 8. 1. 3. 3. 5. 4.]
[6 8 0 8 8 1 3 3 5 4]
[6. 8. 0. 8. 8. 1. 3. 3. 5. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [23]:
a37 = np.tile(np.arange(5), (5,1))
a37

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [24]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [30]:
a39 = np.linspace(0, 1, 11, endpoint=False)[1:]
a39

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
a40 = np.random.random((10,))
sorted(a40)
a40

array([0.32654962, 0.01974673, 0.4493509 , 0.73873011, 0.28181179,
       0.92502996, 0.58309639, 0.06918812, 0.00890122, 0.80324342])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
a41 = np.random.random((2,3,4))
print(a41)
print(np.sum(a41))

[[[0.69552435 0.28676536 0.42592889 0.5662701 ]
  [0.90709374 0.8501014  0.83474466 0.78664801]
  [0.88938026 0.27284503 0.08016885 0.70732156]]

 [[0.64136742 0.70676274 0.79883173 0.1012074 ]
  [0.73693663 0.01724008 0.83198857 0.53309202]
  [0.28200104 0.81939021 0.7323542  0.051097  ]]]
13.555061251515195


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [38]:
a42, b42 = np.random.random((2,3,4)), np.random.random((2,3,4))
print(a42)
print(b42)
print(np.array_equal(a42, b42))

[[[0.03586868 0.298503   0.88821929 0.16185903]
  [0.63732879 0.67753888 0.0214173  0.43594414]
  [0.08829048 0.83031096 0.86558953 0.10654857]]

 [[0.13727847 0.2320576  0.66988564 0.50719077]
  [0.3907894  0.46055633 0.61438486 0.86839068]
  [0.01451401 0.81612365 0.77616032 0.20985387]]]
[[[0.81533933 0.57540914 0.4405264  0.2410181 ]
  [0.45323631 0.9645535  0.37439884 0.50658657]
  [0.58103798 0.41527304 0.79273522 0.64466223]]

 [[0.39601846 0.57887401 0.44546393 0.04750412]
  [0.56742658 0.40308997 0.74644153 0.37547664]
  [0.33713334 0.56326548 0.38440544 0.46442315]]]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
a43 = np.zeros((2,3))
print(a43)
print(a43.flags)
a43.flags.writeable = False
print(a43)

[[0. 0. 0.]
 [0. 0. 0.]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[[0. 0. 0.]
 [0. 0. 0.]]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [47]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(Z)
print(R)
print(T)

[[0.78231353 0.01221902]
 [0.46377994 0.71594769]
 [0.87909451 0.45391351]
 [0.55384653 0.39484613]
 [0.80547269 0.02226103]
 [0.74842472 0.62162901]
 [0.43317442 0.04152974]
 [0.08355304 0.69514623]
 [0.80071795 0.77112594]
 [0.12270099 0.14932625]]
[0.78240895 0.85303747 0.98936578 0.68018339 0.80578025 0.97291427
 0.43516065 0.70014955 1.11165842 0.19327147]
[0.01561781 0.99598003 0.47663565 0.61934202 0.02763019 0.69311306
 0.09558089 1.45117525 0.76657408 0.88296458]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [56]:
a45 = np.random.randint(1,11,(2, 3))
print(a45)
print(np.argmax(a45))
ind = np.unravel_index(np.argmax(a45), a45.shape)
print(ind)
a45[ind] = 0
print(a45)

[[6 2 9]
 [1 8 5]]
2
(0, 2)
[[6 2 0]
 [1 8 5]]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [64]:
x, y = np.linspace(0, 1, 5), np.linspace(0, 1, 5)
xx, yy = np.meshgrid(x, y)
print(xx)
print(yy)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [66]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [67]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [70]:
# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [73]:
a50 = np.random.randint(-10, 10, (5, 5))
v = np.random.randint(-10, 10)
pos = np.unravel_index(abs(a50 - v).argmin(), a50.shape)
print(pos)
print(a50)
print(v)

(0, 0)
[[  4   5  -9 -10  -1]
 [ -6   2   0   4   3]
 [ -3   0   6  -8  -1]
 [ -1  -7   4   1  -5]
 [  2   5   4  -2   5]]
4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [74]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/home/yili/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [80]:
a52 = np.random.random((10, 2))
print(a52)
X,Y = np.atleast_2d(a52[:,0], a52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.02534806 0.45340425]
 [0.44818878 0.45829376]
 [0.59008367 0.66281875]
 [0.28618479 0.05256633]
 [0.08406668 0.7238563 ]
 [0.07670006 0.91494956]
 [0.16445768 0.1240141 ]
 [0.10268686 0.65915213]
 [0.09608403 0.64083578]
 [0.67054423 0.31902856]]
[[0.         0.42286899 0.60231283 0.47823304 0.27675294 0.46439326
  0.35756028 0.21980327 0.20033511 0.65904092]
 [0.42286899 0.         0.24892696 0.43687531 0.45067545 0.58867511
  0.43845892 0.39964442 0.39660981 0.26236758]
 [0.60231283 0.24892696 0.         0.68173495 0.50968497 0.57195514
  0.68663522 0.4874106  0.49448852 0.35308016]
 [0.47823304 0.43687531 0.68173495 0.         0.70105774 0.88746193
  0.14114628 0.63373324 0.61822265 0.46769039]
 [0.27675294 0.45067545 0.50968497 0.70105774 0.         0.1912352
  0.60520523 0.06733009 0.08388577 0.71262993]
 [0.46439326 0.58867511 0.57195514 0.88746193 0.1912352  0.
  0.7957891  0.25711406 0.27479829 0.84129231]
 [0.35756028 0.43845892 0.68663522 0.14114628 0.60520523 0.7957891
 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [91]:
a53 = np.random.rand(2,3,4).astype(np.float32) * 100
b53 = a53.view(np.int32)
print(a53)
print(b53)
b53[:] = a53
print(b53)


[[[ 0.24366239 67.71906     1.1312132  55.37463   ]
  [12.603082   99.04504    74.11735    91.78087   ]
  [50.010742   95.40324    87.704834   48.62975   ]]

 [[23.943077   33.63343    64.0629     40.06021   ]
  [33.26952    38.089954   44.023186   55.605843  ]
  [32.979713   67.51488    39.660446   35.21837   ]]]
[[[1048150690 1116172329 1066453912 1113423775]
  [1095345721 1120278287 1117010965 1119326158]
  [1112017664 1119800949 1118791904 1111655645]]

 [[1103072108 1107724450 1115693108 1109409192]
  [1107629053 1108892701 1110448062 1113484386]
  [1107553082 1116145566 1109304396 1108139932]]]
[[[ 0 67  1 55]
  [12 99 74 91]
  [50 95 87 48]]

 [[23 33 64 40]
  [33 38 44 55]
  [32 67 39 35]]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [92]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [93]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [98]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(X)
print(Y)
print(D)
print(G)

[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
[[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]
[[1.41421356 1.11803399 1.         1.11803399 1.41421356]
 [1.11803399 0.70710678 0.5        0.70710678 1.11803399]
 [1.         0.5        0.         0.5        1.        ]
 [1.11803399 0.70710678 0.5        0.70710678 1.11803399]
 [1.41421356 1.11803399 1.         1.11803399 1.41421356]]
[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [101]:
a57 = np.zeros((5,5))
pos = np.random.choice(np.arange(5*5), 3, replace=False)
print(a57)
np.put(a57, pos, 1)
print(pos)
print(a57)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0 23 19]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [114]:
a58 = np.random.random((2,5))
print(a58)
mean = a58.mean(axis=1, keepdims=True)
a58 = a58 - mean
print(mean)
print(a58)

[[0.86316129 0.0243865  0.61051115 0.2845846  0.80759025]
 [0.11762626 0.40513059 0.16606975 0.72318716 0.26546144]]
[[0.51804676]
 [0.33549504]]
[[ 0.34511453 -0.49366026  0.09246439 -0.23346216  0.28954349]
 [-0.21786878  0.06963555 -0.16942529  0.38769212 -0.0700336 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [118]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[:,1].argsort())
print(Z[Z[:,1].argsort()])

[[1 7 7]
 [5 6 4]
 [9 7 5]]
[1 0 2]
[[5 6 4]
 [1 7 7]
 [9 7 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [128]:
a60 = np.random.randint(0, 3, (2,3))
print(a60)
print((a60 == 0).any())

[[1]
 [1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [131]:
a61 = np.random.random((3,4))
v = np.random.random()
# np.flat[]
pos = np.unravel_index(abs(a61 - v).argmin(), a61.shape)
print(pos)
print(a61)
print(v)

9
[[0.49406371 0.82689039 0.37153772 0.01290839]
 [0.48461934 0.27081195 0.47131874 0.62066893]
 [0.86657734 0.88457075 0.69076427 0.03979789]]
0.9791738551053176


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [132]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [133]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [135]:
a64 = np.ones(10)
pos = np.random.randint(0, len(a64), 20)
np.add.at(a64, pos, 1)
print(pos)
print(a64)

[3 7 6 1 6 8 2 2 9 4 2 6 1 0 4 7 6 1 1 1]
[2. 6. 4. 2. 3. 1. 5. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [136]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [139]:
a66 = np.random.random((100, 200, 3))
print(np.unique(a66).shape)

(60000,)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [140]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[49 71 71 54]
 [52 46 51 38]
 [48 50 64 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [141]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.48621928 0.37312506 0.5362721  0.51160811 0.5231448  0.64309891
 0.45786173 0.20491035 0.60732231 0.61350934]


#### 69. How to get the diagonal of a dot product? (★★★)

In [142]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))
# np.sum(A * B.T, axis=1)

array([2.07613858, 1.68088616, 1.34071317, 0.39556253, 1.60283045])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [143]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*3)
Z0[::4] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [145]:
a71, b71 = np.random.random((5,5,3)), np.random.random((5,5))
print(a71 * b71[..., None])

[[[0.02505858 0.1285487  0.33105338]
  [0.15571878 0.45393172 0.61952436]
  [0.32545745 0.3751776  0.24656747]
  [0.20486391 0.32709082 0.73959689]
  [0.16437081 0.42883591 0.09780611]]

 [[0.70384464 0.31117164 0.01285631]
  [0.2618962  0.56127131 0.10408066]
  [0.35447475 0.5522929  0.82752033]
  [0.43371759 0.41040412 0.13305609]
  [0.40093793 0.4633172  0.05517077]]

 [[0.04082064 0.41298664 0.71199386]
  [0.83714497 0.62844384 0.74139381]
  [0.08876067 0.25246474 0.33631732]
  [0.82544555 0.52143911 0.46585919]
  [0.24309954 0.54468027 0.63524991]]

 [[0.09381908 0.05331403 0.01377726]
  [0.02287387 0.07801364 0.00149319]
  [0.05608993 0.02744252 0.11266628]
  [0.38265713 0.18063654 0.44839707]
  [0.69337508 0.55026767 0.78881714]]

 [[0.27773791 0.64367769 0.19882666]
  [0.08214668 0.13612743 0.14646847]
  [0.36935785 0.34412127 0.07197887]
  [0.13276784 0.00456769 0.18587276]
  [0.02360577 0.00278135 0.03831317]]]


#### 72. How to swap two rows of an array? (★★★)

In [147]:
a72 = np.random.random((2, 3))
print(a72)
a72[[0, 1]] = a72[[1, 0]]
print(a72)

[[0.06947475 0.00968703 0.18825108]
 [0.77986031 0.86302225 0.98636314]]
[[0.77986031 0.86302225 0.98636314]
 [0.06947475 0.00968703 0.18825108]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [148]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 64) ( 3, 95) ( 4, 51) ( 4, 80) (14, 17) (14, 59) (17, 59) (22, 39)
 (22, 87) (23, 25) (23, 56) (25, 56) (28, 50) (28, 66) (30, 32) (30, 55)
 (32, 55) (33, 47) (33, 85) (39, 50) (39, 73) (39, 87) (47, 85) (50, 66)
 (50, 73) (51, 80) (64, 95) (71, 73) (71, 98) (73, 98)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [150]:
a74 = np.random.randint(0, 10, (5))
origin = np.repeat(np.arange(5), a74)
print(a74)
print(origin)
print(np.bincount(origin))

[0 1 3 5 2]
[1 2 2 2 3 3 3 3 3 4 4]
[0 1 3 5 2]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [151]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [154]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [156]:
Z = np.random.randint(0,2,100)
print(Z)
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
print(np.negative(Z, out=Z))

[0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1
 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 1]
[1 1 0 0 0 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0
 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1
 0 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 0 0]
[ 0.6109796   0.81873989  0.54136906  0.70623272 -0.41661138  0.63727137
  0.31331019 -0.18929413  0.70963192  0.97081339 -0.79102276 -0.16660384
  0.17057515  0.08779687 -0.4373749  -0.25753499  0.84028433 -0.02870541
 -0.4258535  -0.20128299  0.99835916 -0.72070891 -0.83185258  0.79704432
 -0.36553186 -0.58309305 -0.76005616  0.40142869  0.49139676 -0.94619067
 -0.82882513 -0.7768419  -0.77949785 -0.40271261 -0.42545245 -0.52449575
 -0.16509328  0.38032127 -0.33761701 -0.16785229  0.68818188  0.63082483
  0.10430117  0.11980457 -0.10636875 -0.65809757  0.10957728  0.92514021
  0.1203

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [5]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.07026595 15.93764404  2.94232446  3.66175496  1.14341305 10.56028058
 17.32600266  2.32854163  9.37806167  2.91029176]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [7]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[2.38979732e+00 2.20136898e+00 9.77231670e+00 2.74820425e+00
  3.96997218e+00 2.21159819e+00 8.00806971e+00 7.47225825e+00
  9.19374371e+00 6.69819782e+00]
 [5.29316299e+00 4.98557616e+00 1.24959695e+01 6.90406905e-01
  1.08556804e+00 5.12165042e+00 8.61448779e+00 1.03532401e+01
  1.17592849e+01 7.43237479e+00]
 [6.09708615e+00 5.33503435e+00 1.35374479e+01 5.68020777e-01
  2.29945349e-01 5.74746697e+00 9.81317143e+00 1.08782132e+01
  1.28894605e+01 8.65070247e+00]
 [2.59469689e+00 7.24876441e-01 3.83270136e+00 9.30973356e+00
  9.17238536e+00 1.99289886e+00 2.43352328e+00 3.72578822e+00
  2.94292371e+00 9.73504415e-01]
 [4.76616895e+00 4.13168691e+00 2.69852290e+00 8.68477168e+00
  1.11507126e+01 4.73488460e+00 5.21913808e+00 7.13942288e-01
  2.34330497e+00 3.61413034e+00]
 [1.03956030e+00 2.80187341e+00 7.21361340e+00 6.80195586e+00
  5.56749062e+00 1.66751088e+00 3.09074414e+00 7.35897894e+00
  6.11283042e+00 1.79220065e+00]
 [4.86284781e+00 5.46155967e+00 3.45120137e+00 6.73190767e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [8]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [10]:
a81 = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(a81,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [11]:
a82 = np.random.randint(1,10, (3,4))
print(a82)
u,s,v = np.linalg.svd(a82)
print(u)
print(s, len(s))
print(v)

[[8 2 4 8]
 [6 6 4 9]
 [4 6 1 7]]
[[-0.58647954 -0.74700527  0.31308924]
 [-0.64877908  0.20184    -0.73372087]
 [-0.48489943  0.63343803  0.60301643]]
[19.94262672  4.45215539  1.21241575] 3
[[-0.52771927 -0.39989868 -0.27207719 -0.69826028]
 [-0.50116177  0.79010217 -0.34752225  0.0616744 ]
 [ 0.42432174 -0.1303581  -0.89037949  0.10090682]
 [-0.53879524 -0.44589951 -0.11147488  0.70600756]]


#### 83. How to find the most frequent value in an array?

In [13]:
a83 = np.random.randint(1, 10, (100))
cnt = np.bincount(a83)
print(a83)
print(cnt)
print(cnt.argmax(), cnt.max())

[6 2 2 1 1 7 6 7 9 7 2 8 2 5 5 5 8 7 1 1 2 1 6 9 1 3 5 9 7 3 5 3 7 7 9 8 6
 4 9 3 2 5 3 2 5 4 2 5 2 1 9 2 2 9 6 4 5 5 3 2 1 1 2 5 2 5 5 1 1 4 3 1 8 2
 9 9 3 5 4 5 2 6 6 5 2 1 2 3 2 2 2 2 3 3 6 7 5 3 2 8]
[ 0 13 23 12  5 17  8  8  5  9]
2 23


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [14]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
answer(85)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [18]:
a86, b86 = np.random.randint(1, 10, (3, 4, 4)), np.random.randint(1, 10, (3, 4, 1))
ret = np.tensordot(a86, b86, [(0,2), (0,1)])
print(ret)

[[245]
 [289]
 [368]
 [383]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
answer(87)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [19]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [23]:
a89 = np.arange(10)
print(a89)
np.random.shuffle(a89)
print(a89)
n = 3
pos = np.argpartition(-a89, n)
print(a89[pos[:n]])

[0 1 2 3 4 5 6 7 8 9]
[3 6 9 4 7 0 2 5 8 1]
[9 8 7]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [24]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [25]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [28]:
x = np.random.rand(int(5e7))

# print(len(x))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

50000000


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [29]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [30]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[1 0 4]
 [0 1 1]
 [1 0 1]
 [4 2 4]
 [3 3 2]
 [3 3 1]
 [2 0 2]
 [4 1 2]
 [1 1 4]
 [4 2 3]]
[[1 0 4]
 [0 1 1]
 [1 0 1]
 [4 2 4]
 [3 3 2]
 [3 3 1]
 [2 0 2]
 [4 1 2]
 [1 1 4]
 [4 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [31]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [36]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(Z)
print(uZ)

[[1 0 1]
 [0 1 0]
 [1 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [37]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [38]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [39]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30809138  0.1064733 ]
